# Generated by Django 3.1.2 on 2020-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('user_id', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('mobile', models.CharField(max_length=30)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
