# Generated by Django 3.1.2 on 2020-11-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
